////////////////////////////////////////////////////////////////////////
// Class:       RawDigitOverlayMicroBooNEAna
// Module Type: analyzer
// File:        RawDigitOverlayMicroBooNEAna_module.cc
//
// Generated at Tue Nov 10 13:06:09 2015 by Wesley Ketchum using artmod
// from cetpkgsupport v1_08_07.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "art/Framework/Services/Optional/TFileService.h"

#include "TTree.h"

#include "DataOverlay/RawDigitAdderAna.hh"

namespace mix {
  class RawDigitOverlayMicroBooNEAna;
}

class mix::RawDigitOverlayMicroBooNEAna : public art::EDAnalyzer {
public:
  explicit RawDigitOverlayMicroBooNEAna(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  RawDigitOverlayMicroBooNEAna(RawDigitOverlayMicroBooNEAna const &) = delete;
  RawDigitOverlayMicroBooNEAna(RawDigitOverlayMicroBooNEAna &&) = delete;
  RawDigitOverlayMicroBooNEAna & operator = (RawDigitOverlayMicroBooNEAna const &) = delete;
  RawDigitOverlayMicroBooNEAna & operator = (RawDigitOverlayMicroBooNEAna &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

private:

  std::string                   fRawDigitModule1;
  std::string                   fRawDigitModule2;
  std::string                   fRawDigitModuleSum;
  size_t                        fChannelSampleInterval;
  std::vector<raw::ChannelID_t> fChannelsSpecial;  
  bool                          fPrintBadOverlays;
  std::string                   fInput1Label;
  std::string                   fInput2Label;
  std::string                   fSumLabel;

  mix::RawDigitAdderAna fAnaAlg;
  

};


mix::RawDigitOverlayMicroBooNEAna::RawDigitOverlayMicroBooNEAna(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p),
  fRawDigitModule1(p.get<std::string>("RawDigitModule1")),
  fRawDigitModule2(p.get<std::string>("RawDigitModule2")),
  fRawDigitModuleSum(p.get<std::string>("RawDigitModuleSum")),
  fChannelSampleInterval(p.get<size_t>("ChannelSampleInterval",100)),
  fChannelsSpecial(p.get< std::vector<raw::ChannelID_t> >("ChannelsToPrint",std::vector<raw::ChannelID_t>())),
  fPrintBadOverlays(p.get<bool>("PrintBadOverlays",true)),
  fInput1Label(p.get<std::string>("Label1",fRawDigitModule1)),
  fInput2Label(p.get<std::string>("Label2",fRawDigitModule2)),
  fSumLabel(p.get<std::string>("LabelSum",fRawDigitModuleSum)),
  fAnaAlg(fChannelSampleInterval,fChannelsSpecial,fPrintBadOverlays,fInput1Label,fInput2Label,fSumLabel)
{
}

void mix::RawDigitOverlayMicroBooNEAna::analyze(art::Event const & e)
{
  art::ServiceHandle<art::TFileService> tfs;

  
}

DEFINE_ART_MODULE(mix::RawDigitOverlayMicroBooNEAna)
